# config/config.yaml
samples_tsv: "config/samples.tsv"

qc:
  percent_top: [20]
  min_cells_per_gene: 3
  nmads_total_counts: 5
  nmads_n_genes: 5
  nmads_pct_top: 5
  nmads_pct_mito: 3
  max_pct_mito: 8
  keep_doublets: false    # drop doublets by default

tools:
  emptydrops: {lower: 100, fdr_cutoff: 0.01}        # or {lower: 100, fdr_cutoff: 0.01} or null
  soupx: null             # or {raw_10x_dir: "/path/outs/raw_feature_bc_matrix", layer_out: "soupx_corrected"}
  doublets:               # choose one of: null | scdblfinder | scrublet
    method: "scrublet" # or "scrublet"
    params:
      batch_key: null     # used only for scDblFinder
      # scrublet params (if using scrublet):
      # expected_doublet_rate: 0.06
      # min_counts: 2
      # min_cells: 3

integration:
  common:
    batch_key: "sample"
    n_top_genes: 3000
    pca_comps: 50
    neighbors_k: 15
    umap_min_dist: 0.30
    cluster_resolution: 1.0

  runs:
    - name: "unintegrated"
      method: "none"
    - name: "bbknn"
      method: "bbknn"
    - name: "harmony"
      method: "harmony"
    - name: "scvi"
      method: "scvi"
      n_latent: 30
      max_epochs: 200

  envs:  # optional overrides
    integrate:
      none:    "environments/scanpy.yaml"
      bbknn:   "environments/scanpy.yaml"
      harmony: "environments/harmony.yaml"
      scvi:    "environments/scvi.yaml"
    graph:
      none:    "environments/scanpy.yaml"
      bbknn:   "environments/bbknn.yaml"
      harmony: "environments/scanpy.yaml"
      scvi:    "environments/scanpy.yaml"